/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 k*/
import java.awt.*;  
import java.awt.event.*; 

/**
 *
 * @author elton
 */
public class MessageFrame extends javax.swing.JFrame {

    /**
     * Creates new form MessageFrame
     */
  private MembershipManagement membership;
  private Coach coach;
  private int who;
  private String name;
    public MessageFrame(MembershipManagement membership,Coach coach,Boolean dog) {
      this.membership = membership;
      this.coach = coach;
      this.who=1;
        initComponents();
    }
    public MessageFrame(MembershipManagement membership,String name,Boolean dog) {
      this.membership = membership;
      this.name = name;
      this.who=3;
        initComponents();
    }
    public MessageFrame(MembershipManagement membership,int who,Boolean dog)
    {
      this.membership = membership;
      this.who = who ;
      initComponents();
    }  
    public MessageFrame(MembershipManagement membership,Coach coach)
    {
      
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageFrame(membership,coach,true).setVisible(true);
            }
        });
      
    }
    public MessageFrame(MembershipManagement membership,String name)
    {
      
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageFrame(membership,name,true).setVisible(true);
            }
        });
      
    }
    public MessageFrame(MembershipManagement membership,int who)
    {
      java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageFrame(membership,who,true).setVisible(true);
            }
        });
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        instructionLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTxt = new javax.swing.JTextArea();
        sendBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        sendBtn.addActionListener(new MsgButton());
        cancelBtn.addActionListener(new CloseFrame());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        instructionLbl.setText("Please enter the message you would like to send");

        msgTxt.setColumns(20);
        msgTxt.setRows(5);
        jScrollPane1.setViewportView(msgTxt);

        sendBtn.setText("Send");

        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(instructionLbl)
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(instructionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sendBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }
    
    private class MsgButton implements ActionListener {
      public void actionPerformed(ActionEvent e) {
        String message = msgTxt.getText();
        
     
        if (who==1){
          String[][] memberNames = coach.getSession().getMemberNames();
          
          for (int x = 0; x < memberNames.length; x++){
            membership.messageSystem.createMessage(memberNames[x][0],message);
          }
        }
        else if(who==2){
          
          membership.messageSystem.createMessage("bossman444",message);  
        }
        
      
      else if(who==0)
      {
        for(int i =0;i < 12;i++)
        {
          membership.messageSystem.createMessage(membership.coaches.get(i).getName(),message); 
          
        }  
        
      }
      else if(who==3)
      {
        String[][] memberNames;
       for(int i = 0;i<membership.sessions.size();i++)
       {
         memberNames = membership.sessions.get(i).getMemberNames();
         for(int j = 0;j<memberNames.length;j++)
         {
          if(memberNames[j][0].equals(name))
               {
                 membership.messageSystem.createMessage(membership.coaches.get(j).getName(),message);
               }
           
         }  
       }  
        
      }
      System.out.println("Message was Sent");
      if(who==1 || who==2)
      {
        CoachFrame coachFrame = new CoachFrame(membership,membership.coaches.get(membership.currCoach));
        dispose();
      }
      if (who==0)
      {
      TreasurerLoginFrame treasurerLoginFrame = new TreasurerLoginFrame(membership);
      }  
        if(who==3)
        {
          MemberFrame memberFrame = new MemberFrame(membership,name);
          dispose();
        }  
      }
      
    }  
    private class CloseFrame implements ActionListener {
      public void actionPerformed(ActionEvent e) {
         if(who==1 || who==2)
      {
        CoachFrame coachFrame = new CoachFrame(membership,membership.coaches.get(membership.currCoach));
        dispose();
      }
      if (who==0)
      {
      TreasurerLoginFrame treasurerLoginFrame = new TreasurerLoginFrame(membership);
      }  
        if(who==3)
        {
          MemberFrame memberFrame = new MemberFrame(membership,name);
          dispose();
        }  
      }
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel instructionLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgTxt;
    private javax.swing.JButton sendBtn;
    // End of variables declaration                   
}
