
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class TreasurerFrame extends javax.swing.JFrame {

    /**
     * Creates new form POSFramek
     */
    public MembershipManagement membership;
    public TreasurerFrame(MembershipManagement membership,Boolean dog) {
        this.membership = membership;
        initComponents();
    }
    public TreasurerFrame(MembershipManagement membership) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreasurerFrame(membership,true).setVisible(true);
            }
        });
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBtn = new javax.swing.JButton();
        invoiceBtn = new javax.swing.JButton();
        memStatBtn = new javax.swing.JButton();
        debtStatBtn = new javax.swing.JButton();
        treasurerLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new LogoutAction());

        invoiceBtn.setText("Session Invoice");
        invoiceBtn.addActionListener(new launchInvoice());

        memStatBtn.setText("Member Status");
        memStatBtn.addActionListener(new launchMemStat());

        debtStatBtn.setText("Debt Status");
        debtStatBtn.addActionListener(new launchDebtStat());

        treasurerLbl.setText("Treasurer");
        treasurerLbl.setToolTipText("");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(treasurerLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGap(128, 128, 128)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(debtStatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(memStatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(invoiceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(treasurerLbl)
                       
                        ))
                .addGap(64, 64, 64)
                .addComponent(invoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(memStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(debtStatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }
    
    private class launchInvoice implements ActionListener {
        public void actionPerformed(ActionEvent e) {
       
          System.out.println("Invoice");
          
    }
    
}
    private class LogoutAction implements ActionListener {
        public void actionPerformed(ActionEvent e) {
          
        TreasurerLoginFrame treasurerLoginFrame = new TreasurerLoginFrame(membership);
                  dispose();
        }
    }
    private class launchMemStat implements ActionListener {
        public void actionPerformed(ActionEvent e) {
       
          System.out.println("Member Status");
          
    }
  }
    
    private class launchDebtStat implements ActionListener {
        public void actionPerformed(ActionEvent e) {
       
          System.out.println("Debt Status");
          
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton invoiceBtn;
    private javax.swing.JButton memStatBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton debtStatBtn;
    private javax.swing.JLabel treasurerLbl;
    
    // End of variables declaration//GEN-END:variables
}
