/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;  
import java.awt.event.*; 
import javax.swing.*;
import javax.swing.event.*;
import java.util.*;
/**
 *
 * @author elton
 */
public class TreasurerAccountsFrame extends javax.swing.JFrame {

    /**
     * Creates new form TreasurerAccountsFrame
     */
  private MembershipManagement membership;
  private Treasurer treasurer;
    public TreasurerAccountsFrame(MembershipManagement membership,boolean dog) {
        this.membership = membership;
        this.treasurer = new Treasurer(1500);
        initComponents();
    }
    
    public TreasurerAccountsFrame(MembershipManagement membership)
      {
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreasurerAccountsFrame(membership,true).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sessionList = new javax.swing.JList<>();
        sessionList.addListSelectionListener(new DropSelect());
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceTxt = new javax.swing.JTextArea();
        invoiceLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        backBtn.addActionListener(new BackAction());
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sessionList.setModel(new javax.swing.AbstractListModel<String>() {
            
            String[] strings = { "Session 0", "Session 1", "Session 2", "Session 3", "Session 4", "Session 5", "Session 6", "Session 7", "Session 8", "Session 9", "Session 10", "Session 11"};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
            
        });
        jScrollPane1.setViewportView(sessionList);

        invoiceTxt.setColumns(20);
        invoiceTxt.setRows(5);
        jScrollPane2.setViewportView(invoiceTxt);

        invoiceLbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        invoiceLbl.setText("INVOICE");

        backBtn.setText("Back");
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(invoiceLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(invoiceLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreasurerAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreasurerAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreasurerAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreasurerAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
     private class BackAction implements ActionListener {
      public void actionPerformed(ActionEvent e) {
        TreasurerFrame treasurerFrame = new TreasurerFrame(membership);
        dispose();
        }
     }
     //Action listener for the sessionlist selection
      private class DropSelect implements ListSelectionListener{
          public void valueChanged(ListSelectionEvent e){
              String value = sessionList.getSelectedValue();
              String[] sessionNumber = value.split(" ");
              int num = Integer.parseInt(sessionNumber[1]);
              Session session = membership.getSession(num);
          
              String invoice = treasurer.profitInvoice(session,num);
             // System.out.println(session.getMemberNames());
              
              invoiceTxt.setText(invoice);
          }
      }
      
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel invoiceLbl;
    private javax.swing.JTextArea invoiceTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> sessionList;
    // End of variables declaration                   
}
